const C=window.BF_CARDS,H=['Crow','Raven','Swan','Owl','Falcon','Hawk'];const $=id=>document.getElementById(id);let st={};
const decks={Crow:['BF-001','BF-025','BF-043','BF-061','BF-067','BF-071','BF-069','BF-070','BF-072','BF-068'],Raven:['BF-002','BF-026','BF-044','BF-056','BF-068','BF-069','BF-070','BF-071','BF-072','BF-067'],Swan:['BF-003','BF-027','BF-045','BF-057','BF-069','BF-071','BF-070','BF-068','BF-072','BF-067'],Owl:['BF-004','BF-028','BF-046','BF-058','BF-070','BF-069','BF-068','BF-071','BF-072','BF-067'],Falcon:['BF-005','BF-029','BF-047','BF-059','BF-067','BF-072','BF-068','BF-069','BF-070','BF-071'],Hawk:['BF-006','BF-030','BF-048','BF-060','BF-069','BF-068','BF-070','BF-071','BF-072','BF-067']};
const by=id=>C.find(c=>c.id===id),cards=ids=>ids.map(by).filter(Boolean),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function init(){H.forEach(h=>{$('playerHouse').add(new Option(h,h));$('aiHouse').add(new Option(h,h))});$('aiHouse').value='Raven';$('start').onclick=start;$('ability').onclick=ability;$('event').onclick=eventPlay;$('resolve').onclick=resolve;$('save').onclick=save;$('again').onclick=()=>location.reload();$('export').onclick=exportCSV;showHistory()}
function start(){st={ph:$('playerHouse').value,ah:$('aiHouse').value,ps:0,os:0,clash:1,spent:false,event:false,sel:null,lead:null,sup:null,oppLead:null,oppSup:null,log:[],records:load()};st.deck=shuffle(cards(decks[st.ph]));st.odeck=shuffle(cards(decks[st.ah]));drawHands();$('setup').classList.add('hidden');$('game').classList.remove('hidden');log(`Match begins: ${st.ph} vs ${st.ah}.`);render()}
function drawHands(){st.hand=[];st.ohand=[];let L=st.deck.find(c=>c.type==='Legend');if(L){st.hand.push(L);st.deck=st.deck.filter(c=>c!==L)}let OL=st.odeck.find(c=>c.type==='Legend');if(OL){st.ohand.push(OL);st.odeck=st.odeck.filter(c=>c!==OL)}while(st.hand.length<5&&st.deck.length)st.hand.push(st.deck.shift());while(st.ohand.length<5&&st.odeck.length)st.ohand.push(st.odeck.shift())}
function cardEl(c,click){let d=document.createElement('div');d.className='card'+(st.sel===c?' selected':'');d.innerHTML=`<img src="${c.art}" alt="${c.name}"><b>${c.name}</b><small>${c.house} · ${c.type}</small><div class="stats"><span>STR ${c.str}</span><span>SPD ${c.spd}</span></div>`;if(click)d.onclick=()=>{st.sel=c;render()};return d}
function render(){['hand','yourLine','oppLine'].forEach(id=>$(id).innerHTML='');st.hand.forEach(c=>$('hand').appendChild(cardEl(c,true)));[st.lead,st.sup].filter(Boolean).forEach(c=>$('yourLine').appendChild(cardEl(c,false)));[st.oppLead,st.oppSup].filter(Boolean).forEach(c=>$('oppLine').appendChild(cardEl(c,false)));$('ps').textContent=st.ps;$('os').textContent=st.os;$('clash').textContent=st.clash;$('log').textContent=st.log.join('\n');let p='Choose a Legend to lead.';if(st.lead&&!st.sup)p='Choose an Ally/Beast support, or resolve.';if(st.lead)p+=' Tap a card in hand, then tap your field.';$('phase').textContent=p;$('yourLine').onclick=place}
function place(){let c=st.sel;if(!c||!st.hand.includes(c))return;if(!st.lead&&c.type==='Legend'){st.lead=c;st.hand=st.hand.filter(x=>x!==c);aiCommit();log(`${c.name} leads.`)}else if(st.lead&&!st.sup&&['Ally','Beast'].includes(c.type)){st.sup=c;st.hand=st.hand.filter(x=>x!==c);log(`${c.name} supports.`)}st.sel=null;render()}
function aiCommit(){st.oppLead=st.ohand.find(c=>c.type==='Legend')||st.ohand[0];st.ohand=st.ohand.filter(c=>c!==st.oppLead);let ss=st.ohand.filter(c=>['Ally','Beast'].includes(c.type));st.oppSup=ss.sort((a,b)=>(b.str+b.spd*.2)-(a.str+a.spd*.2))[0]||null;if(st.oppSup)st.ohand=st.ohand.filter(c=>c!==st.oppSup);log(`Opponent leads ${st.oppLead.name}${st.oppSup?' with '+st.oppSup.name:''}.`)}
function base(line,sup,house){let v=(line?.str||0)+(sup?.str||0),sp=Math.max(line?.spd||0,sup?.spd||0);if(house==='Raven'&&sup?.id==='BF-026')v+=2;if(house==='Raven'&&sup?.id==='BF-044')v+=1;if(house==='Falcon'&&['BF-029','BF-047'].includes(sup?.id))v+=1;if(house==='Owl'&&sup?.id==='BF-028'){v+=1;sp+=1}if(house==='Owl'&&sup?.id==='BF-046'&&st.oppSup)v+=1;if(house==='Crow'&&sup?.id==='BF-043'){v+=1;sp=Math.max(sp,Math.max(st.oppLead?.spd||0,st.oppSup?.spd||0))}return {v,sp}}
function ability(){if(!st.lead||st.spent)return log('No unused Legend ability available.');let me=base(st.lead,st.sup,st.ph),op=base(st.oppLead,st.oppSup,st.ah);if(st.ph==='Raven'&&me.v<=op.v){st.abil=2;log('Aurelian invokes Legacy: +2 Strength.')}else if(st.ph==='Crow'){st.abil=st.oppSup?-3:2;log(st.oppSup?'Corvane exposes support: opponent -3.':'Corvane finds an opening: +2.')}else if(st.ph==='Owl'){st.abil=st.oppSup?-3:2;log(st.oppSup?'Orun forecasts support: opponent -3.':'Orun forecast: +2.')}else if(st.ph==='Swan'){st.abil=-1;log('Aurelia suppresses support: opponent -1.')}else if(st.ph==='Falcon'){st.speed=1;log('Kaedran gains priority: +1 Speed.')}else if(st.ph==='Hawk'&&st.sup){st.abil=1;log('Hadrik strengthens allied support: +1.')}else log('Ability has no valid target.');st.spent=true;render()}
function eventPlay(){if(st.event)return log('Only one Event per Clash.');let evs=st.hand.filter(c=>c.type==='Event');if(!evs.length)return log('No Event in hand.');let me=base(st.lead,st.sup,st.ph),op=base(st.oppLead,st.oppSup,st.ah),e=evs.find(x=>x.id==='BF-072'&&op.v-me.v>=3)||evs.find(x=>x.id==='BF-071')||evs.find(x=>x.id==='BF-067'&&['Crow','Falcon'].includes(st.ph))||evs[0];st.hand=st.hand.filter(c=>c!==e);st.event=e;st.evMod=0;st.oppEv=0;if(e.id==='BF-072')st.evMod=4;else if(e.id==='BF-071')st.oppEv=-2;else if(e.id==='BF-067'&&['Crow','Falcon'].includes(st.ph))st.evMod=2;else st.evMod=1;log(`${e.name} played.`);render()}
function resolve(){if(!st.lead||!st.oppLead)return log('Choose a Legend first.');let me=base(st.lead,st.sup,st.ph),op=base(st.oppLead,st.oppSup,st.ah);let mv=me.v+(st.evMod||0),ov=op.v+(st.oppEv||0),ms=me.sp+(st.speed||0),os=op.sp;if(st.abil>0)mv+=st.abil;if(st.abil<0)ov+=st.abil;if(st.sup?.id==='BF-027')ov-=2;if(st.ph==='Crow'&&st.sup?.id==='BF-025')ov-=1;if(st.oppSup?.id==='BF-027')mv-=2;if(st.ah==='Raven'&&st.oppSup?.id==='BF-026')ov+=2;if(st.ah==='Falcon'&&['BF-029','BF-047'].includes(st.oppSup?.id))ov+=1;if(st.ah==='Owl'&&st.oppSup?.id==='BF-028')ov+=1;let win=mv>ov||mv===ov&&ms>os;if(mv===ov&&ms===os)win=Math.random()<.5;if(win){st.ps++;log(`You take the field ${mv}–${ov}.`)}else{st.os++;log(`Opponent takes the field ${ov}–${mv}.`)}if(st.ps>=3||st.os>=3)return finish();next()}
function next(){st.clash++;st.lead=st.sup=st.oppLead=st.oppSup=st.sel=null;st.event=false;st.evMod=st.oppEv=st.abil=st.speed=0;while(st.hand.length<5&&st.deck.length)st.hand.push(st.deck.shift());while(st.ohand.length<5&&st.odeck.length)st.ohand.push(st.odeck.shift());render();log(`— Clash ${st.clash} —`)}
function finish(){$('game').classList.add('hidden');$('result').classList.remove('hidden');$('winner').value=st.ps>st.os?'Player':'Opponent';$('resultSummary').textContent=`${st.ph} ${st.ps} – ${st.os} ${st.ah} in ${st.clash} Clashes.`;showHistory()}
function log(x){st.log.push(x);if($('log'))$('log').textContent=st.log.join('\n')}
function load(){try{return JSON.parse(localStorage.getItem('bfPlaytests')||'[]')}catch{return []}}
function save(){let r=load();r.push({date:new Date().toISOString(),playerHouse:st.ph,opponentHouse:st.ah,winner:$('winner').value,clashes:st.clash,decisive:$('decisive').value,feel:$('feel').value,notes:$('notes').value});localStorage.setItem('bfPlaytests',JSON.stringify(r));showHistory();alert('Playtest saved on this device.')}
function showHistory(){let r=load();if(!$('history'))return;$('history').textContent=r.length?`${r.length} saved playtest(s).\n`+r.slice(-5).reverse().map(x=>`${x.playerHouse} vs ${x.opponentHouse} — ${x.winner} — ${x.feel}`).join('\n'):'No saved playtests yet.'}
function exportCSV(){let r=load();if(!r.length)return alert('No saved playtests yet.');let k=['date','playerHouse','opponentHouse','winner','clashes','decisive','feel','notes'],q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv=[k.join(','),...r.map(x=>k.map(y=>q(x[y])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='blackfeather_playtests.csv';a.click()}
document.addEventListener('DOMContentLoaded',init);